version: "3.3"

services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=redhat"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=test"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - web_net
    volumes:
      - /root/mysql_data:/var/lib/mysql
  #    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  gunicorn:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./deploy/django.env
#    ports:
#      - "8000:8000"
    networks:
      - web_net
    volumes:
      - static:/static
    restart: always
    depends_on:
      - db


  nginx:
    image: nginx:stable
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/nginx.conf:ro
      - static:/static
    ports:
      - "80:80"
    networks:
      - web_net
    depends_on:
      - gunicorn

networks:
  web_net:
volumes:
  static: